### ISSUE TITLE
WhatsApp won't run because it thinks it's being executed by Chrome <36

### ISSUE THREAD

**Issue by nvesely** [TheGoddessInari/rambox#72]
### Steps to reproduce

1. Try to run WhatsApp using the default profile.
2. Get the error below.

### Expected behavior

It just works.

### Actual behavior

It refuses to run because it's convinced it's running in Chrome <36.

![screenshot from 2018-12-03 21-21-51](https://user-images.githubusercontent.com/3538418/49402845-fbd8ed00-f742-11e8-8490-80f23898763d.png)

### ENVIRONMENT

```sh
$ cat /etc/*release | head -n1
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
```

![screenshot from 2018-12-03 21-22-08](https://user-images.githubusercontent.com/3538418/49402835-f24f8500-f742-11e8-87aa-5785fd0f8622.png)

> Does this happen upstream: yes, no, unknown, or N/A

unkown

**Comment by TheGoddessInari** [comment]
Not sure where this could be coming from, I've tried WhatsApp on both Windows and Linux and haven't had any problems, including today.

**Comment by Gaboris** [comment]
Actually this seems like a global problem for these clients. Even on Franz's repository a bunch of people are saying that it's not working for them no matter the version or the system.

Not sure if this applies here as well and also no idea why you're not having any problems, but the general consensus seems to be that WhatsApp doesn't recognize the user agent properly and freaks out.
A temporary fix is to remove the service and re-add it, but that'll break again after a restart.

**Comment by TheGoddessInari** [comment]
I've reached out to WhatsApp support, if I don't hear back from them, I'll have to add a user agent override.

**Comment by TheGoddessInari** [comment]
Added a user agent override in 347e05b4ce8a0255589f45d6b8bc55f5f8e674aa. Worked to fix it for me.

**Comment by nvesely** [comment]
Still not working for me. I downloaded the latest AppImage via the README and installed it. On that note it would be good if the version field in "About Rambox-OS" included the commit hash. Just to be sure there's no confusion about what's being run and to help debug "unstable" builds.

**Comment by TheGoddessInari** [comment]
You need to clear your data for that tab or load a new tab. For some reason, WhatsApp sets a cookie flagging you.

**Comment by TheGoddessInari** [comment]
There'll be commit and date info in new builds in About dialog, and pre-populated into 'report an issue' link.

This should be fixed with the removal of stale cookies.

**Comment by nvesely** [comment]
I tried refreshing, deleting + re-adding the service, and clearing cookies manually via the Application tab of developer tools. Still getting the warning.

**Comment by TheGoddessInari** [comment]
What's the BuildVersion string for what you're using? I haven't been able to reproduce the bad behavior on either platform since we started telling WhatsApp that we're genuine Chrome 66.

**Comment by nvesely** [comment]
When I downloaded the version I'm running now the latest commit was your fix for this issue. I just tried to download the latest version, but the link to it is broken:

![screenshot from 2018-12-08 17-52-38](https://user-images.githubusercontent.com/3538418/49688988-34494400-fb12-11e8-9038-a6327f0164e3.png)

**Comment by nvesely** [comment]
I'm not familiar with the internals of AppImage. I've been using those builds honestly just because I like the ideas behind AppImage and wanted to test it out: cut out the distro maintainer middleperson and forget about library version incompatibilites between apps.

Anyway, I am running the latest version now (confirmed by build string) and the problem is persisting. I tried clearing all local storage--cookies and cache, deleting the service, restarting the application, and re-adding the service, but am getting the same error still.

**Comment by TheGoddessInari** [comment]
I'm not sure how, but it's ignoring the user agent, specifically on Linux, and only for WhatsApp.

**Comment by wefalltomorrow** [comment]
Same here on Windows 10, I completely removed Rambox and installed from the link in the readme and still have this issue. I tried removing and reinstalling multiple times but it still occured, all Rambox data and registry entries were removed as well.

**Comment by wefalltomorrow** [comment]
Still the same issue, it worked at first but the Whatapp QR code didn't work so I reloaded and the Google Chrome update thing came back. Oh well :/

**Comment by TheGoddessInari** [comment]
Well, it **was** working. I hate WhatsApp. They do this stuff on purpose. :P

**Comment by Ch1llb0** [comment]
I've still got this issue being on 0.5.18... Is there a newer build for Win10 x64 incorporating the aforementioned fixes?

**Comment by TheGoddessInari** [comment]
The current commit hash of 0172bec should fix this, if there's still a problem, I'm going to need to know a lot about your environment.
